// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NFTEventAdapter is an autogenerated mock type for the NFTEventAdapter type
type NFTEventAdapter struct {
	mock.Mock
}

// RunService provides a mock function with given fields:
func (_m *NFTEventAdapter) RunService() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewNFTEventAdapter interface {
	mock.TestingT
	Cleanup(func())
}

// NewNFTEventAdapter creates a new instance of NFTEventAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNFTEventAdapter(t mockConstructorTestingTNewNFTEventAdapter) *NFTEventAdapter {
	mock := &NFTEventAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
